# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Generate copyable POSIX hooks using tools shipped in standard Gitea images."""

import shlex
from string import Template
from urllib.parse import urlsplit


_SCRIPT = Template(r"""#!/bin/sh
# Generated by Plane. Requires Git, curl and standard POSIX/BusyBox tools.
# Contains a workspace integration secret. Keep this code private.
set -eu
export LC_ALL=C
MODE=$mode
API_URL=$api_url
TOKEN=$token
REPOSITORY_URL=$repository_url
RETRY_METADATA_SAFE=0
TEMP_DIR=''
STARTED=0

quote_arg() {
    printf "'"
    printf '%s' "$$1" | sed "s/'/'\\\\''/g"
    printf "'"
}

fail() {
    if [ "$$MODE" = validate ]; then
        printf '%s\n' "[Plane: REJECTED] $$1" >&2
        exit 1
    fi
    printf '%s\n' "[Plane: REPORT FAILED] Push was accepted, but commit links were not fully reported. $$1" >&2
    if [ -n "$$TEMP_DIR" ] && [ -s "$$TEMP_DIR/pending" ]; then
        printf '%s' '[Plane] Retry in this bare repository after fixing the error: env ' >&2
        if [ "$$RETRY_METADATA_SAFE" = 1 ] && [ -n "$$REPOSITORY_URL" ]; then
            quote_arg "PLANE_GITEA_REPOSITORY_URL=$$REPOSITORY_URL" >&2
        elif [ "$$RETRY_METADATA_SAFE" = 1 ]; then
            quote_arg "GITEA_ROOT_URL=$${GITEA_ROOT_URL:-}" >&2
            printf ' ' >&2
            quote_arg "GITEA_REPO_USER_NAME=$${GITEA_REPO_USER_NAME:-}" >&2
            printf ' ' >&2
            quote_arg "GITEA_REPO_NAME=$${GITEA_REPO_NAME:-}" >&2
        fi
        printf ' sh ' >&2
        case "$$0" in /*) hook_path=$$0 ;; *) hook_path=$$PWD/$$0 ;; esac
        quote_arg "$$hook_path" >&2
        printf ' --commits' >&2
        while IFS= read -r pending_sha; do printf ' %s' "$$pending_sha" >&2; done < "$$TEMP_DIR/pending"
        printf '\n' >&2
    fi
    exit 0
}

for utility in git curl timeout date mktemp rm sort grep sed wc head tail tr cat; do
    command -v "$$utility" >/dev/null 2>&1 \
        || fail "Missing required command: $$utility. Check the Gitea runtime; Python and jq are not required."
done
STARTED=$$(date +%s)
umask 077
TEMP_DIR=$$(mktemp -d /tmp/plane-gitea-hook.XXXXXX) || fail 'Unable to create a private temporary directory.'
trap 'rm -rf -- "$$TEMP_DIR"' 0
trap 'fail "Hook interrupted."' 1 2 15
printf 'Authorization: Bearer %s\n' "$$TOKEN" > "$$TEMP_DIR/headers"
unset TOKEN

remaining() {
    elapsed=$$(( $$(date +%s) - STARTED ))
    [ "$$elapsed" -lt 120 ] || return 1
    REMAINING=$$((120 - elapsed))
}

git_cmd() {
    remaining || return 1
    git_timeout=$$REMAINING
    [ "$$git_timeout" -le 30 ] || git_timeout=30
    timeout "$$git_timeout" git --no-replace-objects "$$@" 2>"$$TEMP_DIR/git-error"
}

valid_sha() {
    case "$${#1}" in 40|64) ;; *) return 1 ;; esac
    case "$$1" in *[!0-9a-f]*) return 1 ;; esac
}

is_zero() { case "$$1" in *[!0]*) return 1 ;; esac; }

commit_tip() {
    tip=$$(git_cmd rev-parse --verify "$$1^{}") || fail 'Unable to resolve a Git object.'
    kind=$$(git_cmd cat-file -t "$$tip") || fail 'Unable to read a Git object.'
    if [ "$$kind" = commit ]; then printf '%s\n' "$$tip"; fi
}

: > "$$TEMP_DIR/pending"
if [ "$$MODE" = report ] && [ "$$#" -gt 0 ]; then
    [ "$$1" = --commits ] || fail 'Use --commits followed by complete commit SHAs to retry reporting.'
    shift
    [ "$$#" -gt 0 ] || fail 'Missing retry commit SHAs.'
    for oid do
        valid_sha "$$oid" && ! is_zero "$$oid" || fail 'Invalid retry commit SHA.'
        printf '%s\n' "$$oid" >> "$$TEMP_DIR/pending"
    done
    sort -u "$$TEMP_DIR/pending" > "$$TEMP_DIR/unique"
    cat "$$TEMP_DIR/unique" > "$$TEMP_DIR/pending"
else
    : > "$$TEMP_DIR/tips"
    : > "$$TEMP_DIR/old-tips"
    : > "$$TEMP_DIR/updated-refs"
    refs_count=0
    while read -r old_oid new_oid ref_name extra; do
        refs_count=$$((refs_count + 1))
        [ "$$refs_count" -le 1000 ] || fail 'Too many references; split this push into smaller batches.'
        valid_sha "$$old_oid" && valid_sha "$$new_oid" && [ -n "$$ref_name" ] && [ -z "$$extra" ] \
            || fail 'Invalid Git hook input.'
        git_cmd check-ref-format "$$ref_name" >/dev/null || fail 'Invalid Git reference.'
        printf '%s\n' "$$ref_name" >> "$$TEMP_DIR/updated-refs"
        if [ "$$MODE" = report ] && ! is_zero "$$old_oid"; then commit_tip "$$old_oid" >> "$$TEMP_DIR/old-tips"; fi
        if ! is_zero "$$new_oid"; then commit_tip "$$new_oid" >> "$$TEMP_DIR/tips"; fi
    done
    [ -s "$$TEMP_DIR/tips" ] || exit 0
    sort -u "$$TEMP_DIR/tips" > "$$TEMP_DIR/revisions"
    if [ "$$MODE" = validate ]; then
        git_cmd rev-list --max-count=10001 --stdin --not --all \
            < "$$TEMP_DIR/revisions" > "$$TEMP_DIR/pending" || fail 'Unable to enumerate new commits.'
    else
        git_cmd for-each-ref '--format=%(refname) %(objectname)' > "$$TEMP_DIR/current-refs" \
            || fail 'Unable to read repository references.'
        baseline_count=0
        while read -r ref_name oid; do
            baseline_count=$$((baseline_count + 1))
            [ "$$baseline_count" -le 20000 ] || fail 'Too many repository references to report safely.'
            if ! grep -F -x -q -- "$$ref_name" "$$TEMP_DIR/updated-refs"; then
                commit_tip "$$oid" >> "$$TEMP_DIR/old-tips"
            fi
        done < "$$TEMP_DIR/current-refs"
        sort -u "$$TEMP_DIR/old-tips" > "$$TEMP_DIR/exclusions"
        while IFS= read -r oid; do printf '^%s\n' "$$oid" >> "$$TEMP_DIR/revisions"; done < "$$TEMP_DIR/exclusions"
        git_cmd rev-list --max-count=10001 --stdin < "$$TEMP_DIR/revisions" > "$$TEMP_DIR/pending" \
            || fail 'Unable to enumerate new commits.'
    fi
fi

commit_count=$$(wc -l < "$$TEMP_DIR/pending")
[ "$$commit_count" -le 10000 ] || fail 'More than 10000 new commits; split this push into smaller batches.'
[ "$$commit_count" -gt 0 ] || exit 0

# Repository metadata is validated by Plane; it never changes the fixed API URL.
if [ -z "$$REPOSITORY_URL" ]; then REPOSITORY_URL=$${PLANE_GITEA_REPOSITORY_URL:-}; fi
repository_hint='Set GITEA_ROOT_URL, GITEA_REPO_USER_NAME and GITEA_REPO_NAME, or PLANE_GITEA_REPOSITORY_URL.'
check_repository_url() {
    case "$$1" in http://*|https://*) ;; *) fail "Invalid repository URL configuration. $$repository_hint" ;; esac
    case "$$1" in *'?'*|*'#'*|*'\'*) fail "Invalid repository URL configuration. $$repository_hint" ;; esac
    if printf '%s' "$$1" | grep -q '[[:space:][:cntrl:]]'; then
        fail "Invalid repository URL configuration. $$repository_hint"
    fi
    authority=$${1#*://}
    authority=$${authority%%/*}
    printf '%s\n' "$$authority" | grep -E -q '^([a-zA-Z0-9._-]+|\[[a-fA-F0-9:]+\])(:[0-9]+)?$$' \
        || fail "Invalid repository URL configuration. $$repository_hint"
}
if [ "$$MODE" = report ]; then
    if [ -n "$$REPOSITORY_URL" ]; then
        check_repository_url "$$REPOSITORY_URL"
    else
        [ -n "$${GITEA_ROOT_URL:-}" ] && [ -n "$${GITEA_REPO_USER_NAME:-}" ] && [ -n "$${GITEA_REPO_NAME:-}" ] \
            || fail "Missing Gitea repository environment. $$repository_hint"
        check_repository_url "$$GITEA_ROOT_URL"
        for segment in "$$GITEA_REPO_USER_NAME" "$$GITEA_REPO_NAME"; do
            case "$$segment" in .|..|*'/'*|*'\'*)
                fail "Invalid Gitea repository owner or name. $$repository_hint" ;; esac
            if printf '%s' "$$segment" | grep -q '[[:space:][:cntrl:]]'; then
                fail "Invalid Gitea repository owner or name. $$repository_hint"
            fi
        done
    fi
    RETRY_METADATA_SAFE=1
fi

# Read actual commit objects once; no JSON quoting or interpreter is needed here.
while IFS= read -r oid; do
    raw_size=$$(git_cmd cat-file -s "$$oid") || fail 'Unable to read commit size.'
    [ "$$raw_size" -le 131072 ] || fail 'A Git commit object is too large to process.'
    git_cmd cat-file commit "$$oid" > "$$TEMP_DIR/$$oid" || fail 'Unable to read the actual Git commits.'
    header_bytes=0
    while IFS= read -r header; do
        header_bytes=$$((header_bytes + $${#header} + 1))
        [ -n "$$header" ] || break
    done < "$$TEMP_DIR/$$oid"
    [ "$$((raw_size - header_bytes))" -le 65536 ] || fail 'A commit message exceeds 64 KiB.'
done < "$$TEMP_DIR/pending"

send_batch() {
    remaining || fail 'Work item API operation timed out.'
    http_timeout=$$REMAINING
    [ "$$http_timeout" -le 15 ] || http_timeout=15
    set -- --disable --silent --request POST --proto '=http,https' --max-redirs 0 \
        --proxy '' --noproxy '*' --connect-timeout 5 --max-time "$$http_timeout" \
        --max-filesize 1048576 --header "@$$TEMP_DIR/headers" \
        --output "$$TEMP_DIR/response" --write-out '%{http_code}'
    if [ "$$MODE" = report ]; then
        set -- "$$@" --form-string "repository_url=$$REPOSITORY_URL" \
            --form-string "gitea_root_url=$${GITEA_ROOT_URL:-}" \
            --form-string "gitea_owner=$${GITEA_REPO_USER_NAME:-}" \
            --form-string "gitea_repo=$${GITEA_REPO_NAME:-}"
    fi
    while IFS= read -r batch_sha; do
        set -- "$$@" --form "commits=@$$TEMP_DIR/$$batch_sha;filename=$$batch_sha;type=application/octet-stream"
    done < "$$TEMP_DIR/batch"
    if ! http_status=$$(curl "$$@" "$$API_URL" 2>"$$TEMP_DIR/http-error"); then
        fail 'Cannot reach the work item API. Check DNS, network and trusted TLS certificates in Gitea.'
    fi
    [ "$$(wc -c < "$$TEMP_DIR/response")" -le 1048576 ] || fail 'Work item API response is too large.'
    exec 3< "$$TEMP_DIR/response"
    IFS= read -r marker <&3 || fail 'Empty work item API response.'
    if [ "$$http_status" = 400 ] && [ "$$marker" = PLANE-HOOK-ERROR ]; then
        head -c 5000 <&3 | tr -d '\000-\010\013\014\016-\037\177' >&2
        exec 3<&-
        fail 'Validation or reporting failed. Start titles with an existing work item, e.g. PROJ-123 fix: description.'
    fi
    [ "$$http_status" = 200 ] || fail "Work item API returned HTTP $$http_status; check the integration and its secret."
    [ "$$marker" = PLANE-HOOK-OK ] \
        || fail 'Invalid work item API response. Update Plane before replacing the hook code.'
    while IFS= read -r batch_sha; do
        IFS= read -r returned_sha <&3 || fail 'Incomplete work item API response.'
        [ "$$batch_sha" = "$$returned_sha" ] || fail 'Work item API results do not match the pushed commits.'
    done < "$$TEMP_DIR/batch"
    IFS= read -r marker <&3 || fail 'Incomplete work item API response.'
    [ "$$marker" = PLANE-HOOK-END ] || fail 'Invalid work item API response.'
    if [ "$$MODE" = report ]; then
        while IFS= read -r link <&3; do
            case "$$link" in http://*|https://*)
                printf '[Plane] Work item: %s\n' "$$link" | head -c 2100 | tr -d '\000-\010\013\014\016-\037\177'
                ;; esac
        done
    fi
    exec 3<&-
}

while [ -s "$$TEMP_DIR/pending" ]; do
    : > "$$TEMP_DIR/batch"
    batch_count=0
    batch_bytes=0
    while IFS= read -r oid; do
        raw_size=$$(wc -c < "$$TEMP_DIR/$$oid")
        if [ "$$batch_count" -ge 100 ] || [ "$$((batch_bytes + raw_size))" -gt 524288 ]; then break; fi
        printf '%s\n' "$$oid" >> "$$TEMP_DIR/batch"
        batch_count=$$((batch_count + 1))
        batch_bytes=$$((batch_bytes + raw_size))
    done < "$$TEMP_DIR/pending"
    send_batch
    tail -n "+$$((batch_count + 1))" "$$TEMP_DIR/pending" > "$$TEMP_DIR/remaining"
    cat "$$TEMP_DIR/remaining" > "$$TEMP_DIR/pending"
done
if [ "$$MODE" = validate ]; then verb=Verified; else verb=Reported; fi
printf '[Plane] %s work item references for %s new commit(s).\n' "$$verb" "$$commit_count"
""")


def _url(value):
    if not isinstance(value, str):
        raise ValueError("Invalid URL")
    parsed = urlsplit(value)
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or "?" in value
        or "#" in value
        or "\\" in value
        or any(character.isspace() or ord(character) < 32 or ord(character) == 127 for character in value)
    ):
        raise ValueError("Invalid URL")
    parsed.port
    return value.rstrip("/")


def _generate(mode, api_url, secret, repository_url=""):
    _url(api_url)
    if not isinstance(secret, str) or not secret or any(ord(c) < 32 or ord(c) == 127 for c in secret):
        raise ValueError("Invalid workspace secret")
    return _SCRIPT.substitute(
        mode=shlex.quote(mode),
        api_url=shlex.quote(api_url),
        token=shlex.quote(secret),
        repository_url=shlex.quote(repository_url),
    )


def generate_pre_receive_hook(validation_url, secret):
    return _generate("validate", validation_url, secret)


def generate_hooks(validation_url, commits_url, secret, repository_url=""):
    if repository_url != "":
        repository_url = _url(repository_url)
    return {
        "pre_receive": {"filename": "pre-receive", "content": generate_pre_receive_hook(validation_url, secret)},
        "post_receive": {
            "filename": "post-receive",
            "content": _generate("report", commits_url, secret, repository_url),
        },
    }
