# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate independent validation/report hooks without project or repository bindings."""

from string import Template
from urllib.parse import urlsplit


_SCRIPT = Template("""#!/usr/bin/env python3
# Generated by Plane. Requires Python 3 and Git, with no third-party packages.
# Contains a workspace integration secret. Keep this file private.
import json
import os
import re
import shlex
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

MODE = $mode
API_URL = $api_url
TOKEN = $token
REPOSITORY_URL = $repository_url
MAX_COMMITS = 10000
MAX_MESSAGE_BYTES = 65536
MAX_BATCH_BYTES = 512 * 1024
DEADLINE = time.monotonic() + 120
PENDING = []
PRINTED_LINKS = set()
SHA = r"(?:[0-9a-f]{40}|[0-9a-f]{64})"


class HookError(Exception):
    pass


def remaining():
    seconds = DEADLINE - time.monotonic()
    if seconds <= 0:
        raise HookError("Work item API operation timed out.")
    return seconds


def git(*args):
    try:
        result = subprocess.run(
            ["git", "--no-replace-objects", *args],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            check=True, timeout=min(30, remaining()),
        )
        return result.stdout.decode("utf-8")
    except (subprocess.SubprocessError, OSError, UnicodeError):
        raise HookError("Unable to read the actual Git commits.") from None


def commit_tip(oid):
    target = git("rev-parse", "--verify", oid + "^{}").strip()
    return target if git("cat-file", "-t", target).strip() == "commit" else None


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, request, fp, code, message, headers, new_url):
        return None


# Never forward the workspace secret to redirects or environment-configured proxies.
opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())


def printable(value):
    return "".join(char for char in str(value) if char.isprintable())[:500]


def send_batch(commits):
    body = json.dumps({"commits": commits}, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        API_URL, data=body, method="POST",
        headers={"Authorization": "Bearer " + TOKEN, "Content-Type": "application/json"},
    )
    try:
        with opener.open(request, timeout=min(15, remaining())) as response:
            if response.status != 200:
                raise HookError("Unexpected work item API response.")
            raw = response.read(1024 * 1024 + 1)
        if len(raw) > 1024 * 1024:
            raise HookError("Work item API response is too large.")
        data = json.loads(raw)
    except urllib.error.HTTPError as error:
        raise HookError("Work item API returned HTTP %s; check the integration and its secret." % error.code) from None
    except (urllib.error.URLError, OSError, ValueError):
        raise HookError("Work item API is unavailable or returned invalid data.") from None
    if not isinstance(data, dict) or not isinstance(data.get("results"), list):
        raise HookError("Invalid work item API response.")
    results = data["results"]
    expected = {item["sha"] for item in commits}
    if len(results) != len(commits) or any(not isinstance(item, dict) for item in results):
        raise HookError("Incomplete work item API response.")
    if any(not isinstance(item.get("sha"), str) for item in results) or {item["sha"] for item in results} != expected:
        raise HookError("Work item API results do not match the pushed commits.")
    failures = [item for item in results if item.get("valid") is not True]
    if data.get("valid") is not True or failures:
        for item in failures[:10]:
            error = item.get("error")
            message = (
                error.get("message", "Invalid work item reference")
                if isinstance(error, dict) else "Invalid work item reference"
            )
            print("  %s: %s" % (printable(item["sha"][:12]), printable(message)), file=sys.stderr)
        raise HookError(
            "Start each commit title with an existing work item in this workspace, "
            "e.g. PROJ-123 fix: description."
        )
    if MODE == "report":
        for item in results:
            work_item = item.get("work_item")
            link = work_item.get("url") if isinstance(work_item, dict) else None
            if isinstance(link, str) and link not in PRINTED_LINKS:
                parsed = urllib.parse.urlsplit(link)
                if (parsed.scheme in {"http", "https"} and parsed.hostname
                        and not parsed.username and not parsed.password):
                    print("[Plane] Work item: " + printable(link))
                    PRINTED_LINKS.add(link)


def newly_introduced_commits():
    if MODE == "report" and len(sys.argv) > 1:
        if sys.argv[1] != "--commits" or len(sys.argv) <= 2:
            raise HookError("Use --commits followed by complete commit SHAs to retry reporting.")
        values = list(dict.fromkeys(sys.argv[2:]))
        if any(not re.fullmatch(SHA, oid) or set(oid) == {"0"} for oid in values):
            raise HookError("Invalid retry commit SHA.")
        return values
    tips, old_tips, updated_refs = set(), set(), set()
    for index, line in enumerate(sys.stdin):
        if index >= 1000:
            raise HookError("Too many references; split this push into smaller batches.")
        fields = line.split()
        if len(fields) != 3 or any(not re.fullmatch(SHA, oid) for oid in fields[:2]):
            raise HookError("Invalid Git hook input.")
        old_oid, new_oid, ref_name = fields
        updated_refs.add(ref_name)
        if MODE == "report" and set(old_oid) != {"0"}:
            old = commit_tip(old_oid)
            if old:
                old_tips.add(old)
        if set(new_oid) != {"0"}:
            target = commit_tip(new_oid)
            if target:
                tips.add(target)
    if not tips:
        return []
    command = ["rev-list", "--max-count=%d" % (MAX_COMMITS + 1), *sorted(tips), "--not"]
    if MODE == "validate":
        command.append("--all")
    else:
        # post-receive runs after refs update. Reconstruct the old baseline from
        # stdin's old tips plus refs unaffected by this push, not current --all.
        for line in git("for-each-ref", "--format=%(refname) %(objectname)").splitlines():
            ref_name, oid = line.split()
            if ref_name not in updated_refs:
                target = commit_tip(oid)
                if target:
                    old_tips.add(target)
            if len(old_tips) > 20000:
                raise HookError("Too many repository references to report safely.")
        command.extend(sorted(old_tips))
    return git(*command).splitlines()


def report_metadata(sha, message):
    author, date = git("show", "--no-patch", "--format=%an%x00%aI", sha).rstrip("\\n").split("\\0", 1)
    return {
        "sha": sha, "message": message,
        "url": REPOSITORY_URL + "/commit/" + sha,
        "author_name": author[:255], "committed_at": date,
        "repository_name": urllib.parse.urlsplit(REPOSITORY_URL).path.strip("/")[:255],
    }


def main():
    global PENDING
    commits = newly_introduced_commits()
    if len(commits) > MAX_COMMITS:
        raise HookError("More than %d new commits; split this push into smaller batches." % MAX_COMMITS)
    PENDING = list(commits)
    batch, batch_bytes = [], 20
    for sha in commits:
        if int(git("cat-file", "-s", sha)) > MAX_MESSAGE_BYTES + 65536:
            raise HookError("Commit %s is too large to process." % sha[:12])
        # Preserve the exact stored message; git show %%B appends an extra newline.
        raw = git("cat-file", "commit", sha)
        message = raw.split("\\n\\n", 1)[1] if "\\n\\n" in raw else ""
        if len(message.encode("utf-8")) > MAX_MESSAGE_BYTES:
            raise HookError("Commit %s has a message larger than 64 KiB." % sha[:12])
        item = report_metadata(sha, message) if MODE == "report" else {"sha": sha, "message": message}
        item_bytes = len(json.dumps(item, ensure_ascii=False).encode("utf-8")) + 2
        if batch and (len(batch) >= 100 or batch_bytes + item_bytes > MAX_BATCH_BYTES):
            send_batch(batch)
            PENDING = PENDING[len(batch):]
            batch, batch_bytes = [], 20
        batch.append(item)
        batch_bytes += item_bytes
    if batch:
        send_batch(batch)
        PENDING = PENDING[len(batch):]
    if commits:
        verb = "Reported" if MODE == "report" else "Verified"
        print("[Plane] %s work item references for %d new commit(s)." % (verb, len(commits)))


def fail(message):
    if MODE == "validate":
        print("[Plane: REJECTED] " + printable(message), file=sys.stderr)
        return 1
    print(
        "[Plane: REPORT FAILED] Push was accepted, but commit links were not fully reported. "
        + printable(message), file=sys.stderr,
    )
    if PENDING:
        command = [sys.executable, os.path.realpath(__file__), "--commits", *PENDING]
        print("[Plane] Retry in this bare repository after fixing the error: " + shlex.join(command), file=sys.stderr)
    return 0


try:
    main()
except HookError as error:
    sys.exit(fail(str(error)))
except Exception:
    # Never expose the embedded secret or a provider response in a traceback.
    sys.exit(fail("Unexpected API or Git processing failure."))
""")


def _url(value):
    if not isinstance(value, str):
        raise ValueError("Invalid URL")
    parsed = urlsplit(value)
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or "?" in value
        or "#" in value
        or "\\" in value
        or any(character.isspace() or ord(character) < 32 or ord(character) == 127 for character in value)
    ):
        raise ValueError("Invalid URL")
    parsed.port
    return value.rstrip("/")


def _generate(mode, api_url, secret, repository_url=""):
    _url(api_url)
    if not isinstance(secret, str) or not secret or any(ord(c) < 32 or ord(c) == 127 for c in secret):
        raise ValueError("Invalid workspace secret")
    return _SCRIPT.substitute(
        mode=repr(mode), api_url=repr(api_url), token=repr(secret), repository_url=repr(repository_url)
    )


def generate_pre_receive_hook(validation_url, secret):
    return _generate("validate", validation_url, secret)


def generate_hooks(validation_url, commits_url, secret, repository_url):
    """The repository URL configures report links only; no server binding is created."""
    repository_url = _url(repository_url)
    return {
        "pre_receive": {"filename": "pre-receive", "content": generate_pre_receive_hook(validation_url, secret)},
        "post_receive": {
            "filename": "post-receive",
            "content": _generate("report", commits_url, secret, repository_url),
        },
    }
